import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006837',
        'primary-light': '#E6F2EC',
        'primary-dark': '#004D27',
        'primary-container': '#006837',
        'on-primary': '#ffffff',
        'on-primary-container': '#8ee4a6',
        secondary: '#1A4796',
        'secondary-light': '#EEF2FA',
        danger: '#DC2626',
        'danger-light': '#FEE2E2',
        warning: '#F59E0B',
        'warning-light': '#FEF3C7',
        success: '#16A34A',
        'success-light': '#DCFCE7',
        background: '#F9FAFB',
        surface: '#FFFFFF',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5ee',
        'surface-container': '#ebefe8',
        'surface-container-high': '#e5e9e2',
        'surface-variant': '#dfe4dd',
        'text-primary': '#111827',
        'text-secondary': '#6B7280',
        'text-tertiary': '#9CA3AF',
        'border-default': '#E5E7EB',
        'border-strong': '#D1D5DB',
        'on-surface': '#181d19',
        'on-surface-variant': '#3f4940',
        'inverse-surface': '#2d322d',
        'inverse-on-surface': '#eef2eb',
        outline: '#6f7a70',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        default: ['Inter', 'sans-serif'],
        'page-title': ['Inter', 'sans-serif'],
        'section-header': ['Inter', 'sans-serif'],
        'hero-numbers': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'page-title': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'section-header': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'hero-numbers': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        body: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'data-mono': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'container-margin': '2rem',
        gutter: '1rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '6px',
        md: '10px',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '14px',
        '3xl': '20px',
        full: '9999px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0,0,0,0.04)',
        sm: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        md: '0 4px 8px rgba(0,0,0,0.06), 0 2px 4px rgba(0,0,0,0.04)',
        lg: '0 12px 24px rgba(0,0,0,0.08), 0 4px 8px rgba(0,0,0,0.04)',
        xl: '0 20px 40px rgba(0,0,0,0.10), 0 8px 16px rgba(0,0,0,0.06)',
        focus: '0 0 0 3px rgba(0,104,55,0.15)',
        'card-hover': '0 8px 16px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },
    },
  },
  plugins: [],
};

export default config;
